name: GitHub Workflow

on:
  push:
    branches: [ main ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Ubuntu-Build

    # The CMake configure and build commands are platform agnostic and should
    # work equally well on Windows or Mac. You can convert this to a matrix
    # build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: |
        sudo apt update
        sudo apt install  \
          libxrandr-dev   \
          libxinerama-dev \
          libxcursor-dev  \
          libxi-dev       \
          libgl-dev

    - name: Configure and Build
      run: ${{github.workspace}}/build.sh
